# wrangler.toml

name = "english-words"

main = "./api/data/server.js"

compatibility_date = "2026-07-26"

[assets]
directory = "./www"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "english-words-db"
database_id = "8abe2927-1533-4438-88ab-309dcea86335"
