# wrangler.toml

name = "english-words"

main = "./api/tmp_server_create.js"

compatibility_date = "2026-07-26"

[assets]
directory = "./www"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "english-words-db"
database_id = "8abe2927-1533-4438-88ab-309dcea86335"


[observability]
enabled = false
head_sampling_rate = 1
redact_query_string = false

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1

